from __future__ import annotations

import json
import threading
from concurrent.futures import ThreadPoolExecutor
from datetime import UTC, date, datetime
from hashlib import sha256
from typing import Any

from sqlalchemy import select

from app import models
from app.agent_runner import AgentRunError, run_agent
from app.constraints import build_constraint_payload, normalize_agent_constraints
from app.database import SessionLocal
from app.setup_logic import dumps
from app.solver import solve_month


EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="schedule-generation")
CANCEL_EVENTS: dict[int, threading.Event] = {}
CANCEL_LOCK = threading.Lock()


def _set_run(run_id: int, **values: Any) -> None:
    with SessionLocal() as db:
        run = db.get(models.AgentRun, run_id)
        if run is None:
            return
        for key, value in values.items():
            setattr(run, key, value)
        db.commit()


def _create_schedule(db: Any, team_id: int, year: int, month: int, solver_status: str, config: dict[str, Any], assignments: list[dict[str, Any]]) -> dict[str, Any]:
    schedule = db.scalar(select(models.Schedule).where(models.Schedule.team_id == team_id, models.Schedule.year == year, models.Schedule.month == month))
    if schedule is None:
        schedule = models.Schedule(team_id=team_id, year=year, month=month)
        db.add(schedule)
        db.flush()
    latest = db.scalar(select(models.ScheduleVersion).where(models.ScheduleVersion.schedule_id == schedule.id).order_by(models.ScheduleVersion.version_no.desc()))
    version_no = (latest.version_no + 1) if latest else 1
    input_hash = sha256(dumps(config).encode("utf-8")).hexdigest()
    version = models.ScheduleVersion(
        schedule_id=schedule.id,
        version_no=version_no,
        status=models.ScheduleVersionStatus.DRAFT,
        input_hash=input_hash,
        config_hash=input_hash,
        solver_status=solver_status,
        generated_at=datetime.now(UTC),
        notes="Generated by CP-SAT; awaiting administrator approval.",
    )
    db.add(version)
    db.flush()
    for item in assignments:
        clean = {**item, "local_date": date.fromisoformat(item["local_date"])}
        db.add(models.Assignment(version_id=version.id, team_id=team_id, source=models.AssignmentSource.SOLVER, **clean))
    schedule.active_version_id = version.id
    db.commit()
    return {"schedule_id": schedule.id, "version_id": version.id, "version_no": version_no, "solver_status": solver_status, "assignment_count": len(assignments)}


def run_generation(run_id: int, team_id: int, year: int, month: int, agent_id: str, timeout_seconds: int) -> None:
    cancel_event = threading.Event()
    with CANCEL_LOCK:
        CANCEL_EVENTS[run_id] = cancel_event
    try:
        _set_run(run_id, status=models.AgentRunStatus.RUNNING, started_at=datetime.now(UTC))
        with SessionLocal() as db:
            team = db.get(models.Team, team_id)
            if team is None:
                raise AgentRunError("team not found")
            base = build_constraint_payload(db, team, year, month)
        _set_run(run_id, request_json=dumps(base))
        if cancel_event.is_set():
            _set_run(run_id, status=models.AgentRunStatus.CANCELED, completed_at=datetime.now(UTC))
            return
        result = run_agent(agent_id, base, timeout_seconds, cancel_event)
        constraints = normalize_agent_constraints(result.payload, base)
        _set_run(run_id, constraints_json=dumps(constraints), log_text=f"command={result.command}\nstdout={result.stdout}\nstderr={result.stderr}")
        if constraints["unsupported"]:
            _set_run(
                run_id,
                status=models.AgentRunStatus.FAILED,
                result_json=dumps({"unsupported": constraints["unsupported"]}),
                error_message="지원되지 않는 제약조건이 있어 계산을 중단했습니다.",
                completed_at=datetime.now(UTC),
            )
            return
        if cancel_event.is_set():
            _set_run(run_id, status=models.AgentRunStatus.CANCELED, completed_at=datetime.now(UTC))
            return
        _set_run(run_id, status=models.AgentRunStatus.SOLVING)
        solved = solve_month(constraints, cancel_event, timeout_seconds)
        if solved.status == "CANCELED":
            _set_run(run_id, status=models.AgentRunStatus.CANCELED, result_json=dumps({"conflicts": solved.conflicts}), completed_at=datetime.now(UTC))
            return
        if solved.status == "INFEASIBLE":
            _set_run(run_id, status=models.AgentRunStatus.INFEASIBLE, result_json=dumps({"solver_status": solved.solver_status, "conflicts": solved.conflicts}), completed_at=datetime.now(UTC))
            return
        with SessionLocal() as db:
            result_data = _create_schedule(db, team_id, year, month, solved.solver_status, constraints, solved.assignments)
        result_data.update({"objective_value": solved.objective_value, "conflicts": solved.conflicts})
        _set_run(run_id, status=models.AgentRunStatus.SUCCEEDED, result_json=dumps(result_data), completed_at=datetime.now(UTC))
    except AgentRunError as exc:
        _set_run(
            run_id,
            status=models.AgentRunStatus.CANCELED if cancel_event.is_set() else models.AgentRunStatus.FAILED,
            error_message=str(exc),
            log_text=getattr(exc, "log_text", None),
            completed_at=datetime.now(UTC),
        )
    except Exception as exc:  # Persist unexpected worker failures for the UI instead of losing them.
        _set_run(run_id, status=models.AgentRunStatus.FAILED, error_message=f"generation failed: {exc}", completed_at=datetime.now(UTC))
    finally:
        with CANCEL_LOCK:
            CANCEL_EVENTS.pop(run_id, None)


def submit_generation(run_id: int, team_id: int, year: int, month: int, agent_id: str, timeout_seconds: int) -> None:
    EXECUTOR.submit(run_generation, run_id, team_id, year, month, agent_id, timeout_seconds)


def cancel_generation(run_id: int) -> bool:
    with CANCEL_LOCK:
        event = CANCEL_EVENTS.get(run_id)
    if event is None:
        return False
    event.set()
    return True
